'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { DEFAULTS, KINDS, NAMES, SENSORS, MAX_SENSORS, sensorsFor, isFirmwareLayout, smartPad, formatTime, hex, metadata, pageTouches, pageCrossings, pageMetrics, schedule, selected, simulate, snapshot, validate } from '../lib/eeprom';
import type { Byte, ByteKind, Kind, Settings, Simulation } from '../lib/eeprom';

const COLORS: Record<ByteKind, string> = { old: '#87955d', tmp: '#bf956b', light: '#d6bd65', accel: '#76a4a0', extra1: '#a397bd', extra2: '#b6a18c', extra3: '#87acc0', extra4: '#c99b98', supply: '#bc8caa', crc: '#566f58', pad: '#e7e0d2', mask: '#8e9eb7', meta: '#7c857e', pointer: '#ad7452', free: '#edf0e8' };
const LABELS: Record<ByteKind, string> = { old: 'LIS temp', tmp: 'TMP119', light: 'Light', accel: 'Accel', extra1: 'Sensor 5', extra2: 'Sensor 6', extra3: 'Sensor 7', extra4: 'Sensor 8', supply: 'Supply', crc: 'CRC8', pad: 'Padding', mask: 'Mask', meta: 'Metadata', pointer: 'Pointer', free: 'Unused' };
const ABBR: Record<ByteKind, string> = { old: 'T1', tmp: 'T2', light: 'PD', accel: 'AX', extra1: 'S5', extra2: 'S6', extra3: 'S7', extra4: 'S8', supply: 'V', crc: 'CRC', pad: 'PAD', mask: 'M', meta: 'HDR', pointer: 'PTR', free: '—' };
const SUBTITLES: Record<Kind, string> = { baseline: 'Packed, common-rate records', r1: 'Aligned, common-rate records', partitioned: 'A partition for each sensor', shared: 'One pool for every sensor' };
const DETAILS: Record<Kind, string> = {
  baseline: 'The original log starts at byte 9. Records are packed back-to-back, so their alignment shifts. The raw pointer at 7–8 spans two four-byte pages. Supply is ORed into the LIS temperature low nibble, or stored separately when only the photodiode needs it.',
  r1: 'The pointer moves to 8–9, within one page. A separate supply byte precedes selected payloads; zero padding makes each record a whole number of pages. Every enabled sensor shares one sampling period. Record bytes and the raw pointer have no CRC.',
  partitioned: 'Whole pages are allocated by record size and rate after reserving one record per stream. Each payload gets a supply byte and CRC8. Smart padding adds one byte only when that size has remainder 3 modulo 4. Other strides can still cross pages. If any due stream is full, the whole wake is rejected. R3a uses the FSM; R3b uses the RTC timer.',
  shared: 'All fields due on a wake share one record: mask, supply, fixed-order payloads, CRC8, then zero padding to a four-byte boundary. The record size varies with the due mask. Every enabled stream draws from the same pool. R2a uses the FSM; R2b uses the RTC timer.',
};
const PRESETS = [
  { name: 'Multirate', mask: 15, periods: [120, 60, 30, 10], commonPeriod: 10 },
  { name: 'Original sensors', mask: 13, periods: [120, 60, 30, 10], commonPeriod: 10 },
  { name: 'Matched workload', mask: 13, periods: [10, 10, 10, 10], commonPeriod: 10 },
];

function Legend({ types, sensors = SENSORS }: { types: ByteKind[]; sensors?: Settings['sensors'] }) {
  return <div className="legend">{types.map(type => <span key={type}><i style={{ background: COLORS[type] }} />{sensors?.find(s => s.type === type)?.short ?? LABELS[type]}</span>)}</div>;
}
function colorBlock(bytes: Byte[]) {
  const stops: string[] = [];
  let start = 0;
  while (start < bytes.length) {
    let end = start + 1;
    while (end < bytes.length && bytes[end].type === bytes[start].type) end++;
    stops.push(`${COLORS[bytes[start].type]} ${start / bytes.length * 100}% ${end / bytes.length * 100}%`);
    start = end;
  }
  return `linear-gradient(to right, ${stops.length === 1 ? `${stops[0]}, ${stops[0]}` : stops.join(',')})`;
}
function PageRibbon({ address, bytes, title }: { address: number; bytes: Byte[]; title: string }) {
  const pages = pageTouches(address, bytes.length);
  const minimum = Math.ceil(bytes.length / 4);
  const first = Math.floor(address / 4);
  return <div className="page-ribbon-block">
    <div className="ribbon-title"><b>{title}</b><span>{pageCrossings(address, bytes.length)} {pageCrossings(address, bytes.length) === 1 ? 'crossing' : 'crossings'}</span></div>
    <div className="ribbon-scroll"><div className="page-ribbon" role="img" aria-label={`${title}: ${bytes.length} bytes at address ${address}, ${pages} pages touched, ${pages - minimum} extra pages due to alignment`}>
      {Array.from({ length: pages }, (_, p) => <div className="ribbon-step" key={p}>{p > 0 && <span className={`crossing-arrow ${p >= minimum ? 'extra-crossing' : ''}`} aria-hidden="true">→</span>}<div className={`ribbon-page ${p >= minimum ? 'spill-page' : ''}`}><span className="ribbon-page-label">P{first + p}</span><div>{Array.from({ length: 4 }, (_, col) => { const a = (first + p) * 4 + col, b = bytes[a - address]; return <span key={col} style={{ backgroundColor: b ? COLORS[b.type] : undefined, color: b && ['crc', 'pointer', 'meta'].includes(b.type) ? '#fff' : undefined }} title={b ? `0x${hex(a, 4)} · ${b.label}` : `0x${hex(a, 4)} · outside this write`}>{b ? ABBR[b.type] : '·'}</span>; })}</div><small>{p >= minimum ? 'EXTRA PAGE' : `0x${hex((first + p) * 4, 4)}`}</small></div></div>)}
    </div></div><p className="ribbon-caption">{bytes.length} B · {pages} pages touched · <b>{pages - minimum} extra from alignment</b></p>
  </div>;
}
function PageCrossingExamples({ models, time, onInspect }: { models: Simulation[]; time: number; onInspect: (kind: Kind, address: number) => void }) {
  return <section className="crossing-examples" aria-label="Visual page crossing examples"><div className="section-heading"><div><span className="eyebrow">FOLLOW THE BOUNDARIES</span><h2>See the extra page disappear.</h2></div><span>Latest stored wake at the cursor · four bytes per box</span></div><div className="example-grid">{models.map(sim => {
    const records = sim.records.filter(r => r.time <= time), last = records.at(-1);
    const writes = last ? records.filter(r => r.time === last.time) : [];
    const pointerAddress = sim.kind === 'baseline' ? 7 : sim.kind === 'r1' ? 8 : 136;
    const pointerBytes: Byte[] = Array.from({ length: sim.kind === 'baseline' || sim.kind === 'r1' ? 2 : 4 }, (_, i) => ({ type: i === 3 ? 'crc' : 'pointer', value: null, label: i < 2 ? `Pointer ${i ? 'high' : 'low'} byte` : i === 2 ? 'Generation' : 'CRC8' }));
    return <article className="example-card" key={sim.kind}><div className="example-title"><h3>{NAMES[sim.kind]}</h3><span>t = {formatTime(last?.time ?? null)}</span></div>{writes.length ? writes.map(r => <PageRibbon key={r.address} address={r.address} bytes={r.bytes} title={r.stream === null ? 'Combined record' : sim.sensors[r.stream].short} />) : <p>No supported stream is enabled.</p>}<div className="pointer-example"><PageRibbon address={pointerAddress} bytes={pointerBytes} title={sim.kind === 'shared' || sim.kind === 'partitioned' ? 'One checkpoint slot' : 'Pointer write'} /><p className="fine-print">{sim.kind === 'baseline' ? 'Bytes 7–8 straddle pages 1 and 2. Every successful wake adds one avoidable crossing.' : sim.kind === 'r1' ? 'Bytes 8–9 fit in page 2. No pointer crossing.' : 'Each A/B slot occupies one aligned four-byte page. Periodic checkpoints replace per-record EEPROM pointer writes.'}</p></div><button className="text-button" disabled={!last} onClick={() => last && onInspect(sim.kind, writes[0].address)}>Inspect these bytes ↓</button></article>;
  })}</div><p className="fine-print">Each arrow is one boundary within a logical record or pointer write. A red final page is an extra touch caused by the starting offset. A 16-byte aligned record still crosses three necessary boundaries. R1/R2/R3 send separate page-bounded I²C commands.</p></section>;
}
type CrossingMetric = 'avoidableCrossings' | 'totalCrossings' | 'crossingCommands' | 'payloadCrossings';
function PackingSavings({ models, totals }: { models: Simulation[]; totals: ReturnType<typeof pageMetrics>[] }) {
  const partition = totals[3].packing;
  const saved = (n: number) => n < 0 ? `${Math.abs(n).toLocaleString()} added` : `${n.toLocaleString()} saved`;
  return <section className="packing-savings" aria-labelledby="packing-heading">
    <div className="section-heading"><div><span className="eyebrow">SAME RECORDS / PADDING REMOVED</span><h2 id="packing-heading">What page packing saves.</h2></div></div>
    <p className="metric-definition">Replay exactly the stored records up to the cursor, at the same region starts, with padding removed. Supply, CRC, field order and sample counts stay the same. This comparison isolates padding; it excludes pointers and does not extend the recording when the smaller records would leave more space.</p>
    <div className="table-scroll"><table className="packing-table"><thead><tr><th scope="col">Layout</th><th scope="col">Record boundaries without padding</th><th scope="col">With packing</th><th scope="col">Record boundaries saved</th><th scope="col">Payload boundaries saved</th><th scope="col">Padding bytes</th></tr></thead><tbody>{models.slice(1).map((sim, i) => {
      const p = totals[i + 1].packing;
      return <tr key={sim.kind}><th scope="row">{NAMES[sim.kind]} · {sim.kind === 'partitioned' ? 'smart padding' : 'whole pages'}</th><td>{p.unpaddedRecordCrossings.toLocaleString()}</td><td>{p.recordCrossings.toLocaleString()}</td><td>{saved(p.recordCrossingsSaved)}</td><td>{saved(p.payloadCrossingsSaved)}</td><td>{p.paddingBytes.toLocaleString()} B</td></tr>;
    })}</tbody></table></div>
    <p className="fine-print">Payload boundaries lie inside each sensor’s configured payload. They are a subset of record boundaries and must not be added to them. A payload needs at least ceil(bytes / 4) pages. Padding can change internal payload alignment even when the number of pages in a whole record is unchanged.</p>
    <div className="partition-packing"><h3>R3 partitions · smart-packing savings</h3><p className="metric-definition">Each record stores payload + one supply byte + one CRC byte. Smart padding adds a byte only when that size has a three-byte remainder. Here it produces <b>{saved(partition.recordCrossingsSaved)} record boundaries and {saved(partition.payloadCrossingsSaved)} payload boundaries</b>. Try a 5 B payload: its 7 B record becomes an aligned 8 B record. Default 2/2/2/6 B payloads already produce 4/4/4/8 B records and need no padding.</p>
      <div className="table-scroll"><table className="packing-table"><thead><tr><th scope="col">Partition</th><th scope="col">Stored samples</th><th scope="col">Raw → stored stride</th><th scope="col">Payload boundaries</th><th scope="col">Payload savings vs baseline</th><th scope="col">Extra payload boundaries</th><th scope="col">Smart padding: record / payload</th></tr></thead><tbody>{partition.streams.filter(s => models[3].mask & (1 << s.stream)).map(s => <tr key={s.stream}><th scope="row">{s.name}</th><td>{s.observations.toLocaleString()}</td><td>{models[3].sensors[s.stream].payload + 2} → {smartPad(models[3].sensors[s.stream].payload + 2)} B</td><td>{s.payloadCrossings.toLocaleString()}</td><td>{s.stream === 1 ? 'N/A · no TMP119' : saved(totals[0].packing.streams[s.stream].payloadCrossings - s.payloadCrossings)}</td><td>{s.payloadExtraCrossings.toLocaleString()}</td><td>{saved(s.recordCrossingsSaved)} / {saved(s.payloadCrossingsSaved)}</td></tr>)}</tbody></table></div>
      <p className="fine-print">Baseline comparisons use each layout’s actual stored samples. Choose Matched workload for equal sensor periods; after a capacity limit, sample counts can still differ. Zero extra payload boundaries means the payload touches the minimum number of pages for its length.</p>
    </div>
  </section>;
}
function Overview({ sim, time, active, reference, metric, onInspect }: { sim: Simulation; time: number; active: boolean; reference: ReturnType<typeof pageMetrics>; metric: CrossingMetric; onInspect: (address: number) => void }) {
  const snap = useMemo(() => snapshot(sim, time), [sim, time]);
  const crossings = useMemo(() => pageMetrics(sim, time), [sim, time]);
  const avoided = reference[metric] - crossings[metric];
  const group = sim.capacity / 128;
  const filled = (snap.used + sim.start) / sim.capacity * 100;
  return <article className={`revision revision-${KINDS.indexOf(sim.kind)} ${active ? 'is-selected' : ''}`}>
    <div className="card-top"><span className="eyebrow">0{KINDS.indexOf(sim.kind) + 1} / {sim.exploratory ? 'EXPLORATORY' : sim.kind === 'baseline' ? 'LEGACY' : sim.kind === 'r1' ? 'PROTOCOL 3' : 'FORMAT BYTE 5'}</span><span className={`state ${snap.full ? 'full' : ''}`}>{!sim.mask ? 'N/A' : snap.full ? 'LIMIT' : 'LOGGING'}</span></div>
    <h2><button onClick={() => onInspect(sim.start)} aria-pressed={active}>{NAMES[sim.kind]} <span aria-hidden="true">↗</span></button></h2><p className="subtitle">{SUBTITLES[sim.kind]}</p>
    <div className="crossing-counter"><strong>{(sim.kind === 'baseline' ? crossings[metric] : Math.abs(avoided)).toLocaleString()}</strong><span>{sim.kind === 'baseline' ? (metric === 'payloadCrossings' ? 'payload boundary crossings' : metric === 'avoidableCrossings' ? 'avoidable crossings' : metric === 'crossingCommands' ? 'writes crossing a page' : 'total boundary crossings') : avoided >= 0 ? 'avoided vs baseline' : 'added vs baseline'}</span></div>
    <div className="crossing-breakdown">{sim.kind === 'baseline' ? (metric === 'payloadCrossings' ? `${crossings.payloadExtraCrossings} extra from payload alignment · pointers excluded` : metric === 'avoidableCrossings' ? `${crossings.extraPages} record spills + ${crossings.pointerCrossings} pointer crossings` : metric === 'totalCrossings' ? `${crossings.recordCrossings} record + ${crossings.pointerCrossings} pointer crossings` : `${crossings.crossingRecords} record + ${crossings.pointerWrites} pointer writes`) : `${crossings[metric]} remaining · ${reference[metric] ? `${Math.abs(Math.round(avoided / reference[metric] * 100))}% ${avoided < 0 ? 'increase' : 'reduction'}` : 'baseline has zero crossings'}`}</div>
    <div className="memory-axis"><span>0x0000</span><span>{group} B / tile</span><span>0x{hex(sim.capacity - 1, 4)}</span></div>
    <div className="memory-map" aria-label={`${NAMES[sim.kind]} memory. ${snap.used} record bytes, ${sim.start} metadata bytes.`}>
      {Array.from({ length: 128 }, (_, i) => <button key={i} className="memory-tile" style={{ background: colorBlock(snap.memory.slice(i * group, (i + 1) * group)) }} onClick={() => onInspect(i * group)} title={`Inspect bytes ${i * group}–${(i + 1) * group - 1}`} aria-label={`${NAMES[sim.kind]} bytes ${i * group} to ${(i + 1) * group - 1}`} />)}
    </div>
    <div className="usage-heading"><span><strong>{snap.used.toLocaleString()}</strong> <small>B of records</small></span><span>{filled.toFixed(1)}% incl. metadata</span></div>
    <div className="usage-track" role="img" aria-label={`${filled.toFixed(1)} percent occupied including metadata`}><i style={{ width: `${filled}%` }} /></div>
    <dl className="card-stats"><div><dt>Record boundary crossings</dt><dd>{crossings.recordCrossings}</dd></div><div><dt>Pointer boundary crossings</dt><dd>{crossings.pointerCrossings}</dd></div><div><dt>Extra pages from alignment</dt><dd>{crossings.avoidableCrossings}</dd></div><div><dt>Payload boundary crossings</dt><dd>{crossings.payloadCrossings}</dd></div><div><dt>Extra payload boundaries</dt><dd>{crossings.payloadExtraCrossings}</dd></div><div><dt>Record + pointer page touches</dt><dd>{crossings.totalPageTouches}</dd></div><div><dt>Padding / metadata</dt><dd>{snap.padding} B / {sim.start} B</dd></div></dl>
    <p className="card-foot">{sim.kind === 'baseline' ? 'No TMP119. Original firmware assumes 8 KiB.' : sim.kind === 'r1' ? 'All selected sensors at the common period.' : sim.kind === 'partitioned' ? 'Space freezes per stream at session start.' : 'Variable lengths follow the due sensor mask.'}</p>
    <button className="inspect-button" onClick={() => onInspect(sim.start)}>Inspect layout <span aria-hidden="true">→</span></button>
  </article>;
}
function download(settings: Settings, time: number, models: Simulation[]) {
  const rows = models.map(sim => { const s = snapshot(sim, time); return { revision: NAMES[sim.kind], metadataBytes: sim.start, recordBytes: s.used, paddingBytes: s.padding, counts: s.counts, pointers: s.pointers, firstRejectedWakeSeconds: sim.stopAt, lastStoredWakeSeconds: sim.lastAt, pageCrossings: pageMetrics(sim, time), limit: sim.stopReason, regions: sim.regions }; });
  const blob = new Blob([JSON.stringify({ exploratory: !isFirmwareLayout(settings), sensors: sensorsFor(settings), layoutAssumptions: "Edited payloads use illustrative bytes. Additional sensors extend layout geometry only. R3 reserves 8 pointer bytes per sensor slot; other header sizes are held fixed. TMP119 is excluded from baseline.", kind: 'Densor EEPROM layout simulation; not a device dump or hardware measurement', source: 'README.md and sources/provenance.json', settings, elapsedSecondsInclusive: time, baselineNote: 'TMP119 excluded. Historical firmware assumes 8192 bytes; other capacities are normalized estimates.', results: rows }, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = 'densor-eeprom-comparison.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export default function Home() {
  const [settings, setSettings] = useState<Settings>({ ...DEFAULTS, periods: [...DEFAULTS.periods] });
  const sensors = sensorsFor(settings);
  const exploratory = !isFirmwareLayout(settings);
  const [time, setTime] = useState(240);
  const [metric, setMetric] = useState<CrossingMetric>('avoidableCrossings');
  const [playing, setPlaying] = useState(false);
  const [focus, setFocus] = useState<Kind>('r1');
  const [address, setAddress] = useState(128);
  const [selectedAddress, setSelectedAddress] = useState(128);
  const [stream, setStream] = useState(0);
  const [scheduler, setScheduler] = useState<'fsm' | 'rtc'>('fsm');
  const outcome = useMemo(() => { try { validate(settings); return { models: KINDS.map(k => simulate(k, settings)), error: '' }; } catch (error) { return { models: [] as Simulation[], error: (error as Error).message }; } }, [settings]);
  const maxTime = Math.max(1, ...outcome.models.map(m => m.stopAt ?? 0));
  const shownTime = Math.min(time, maxTime);
  const crossingTotals = useMemo(() => outcome.models.map(m => pageMetrics(m, shownTime)), [outcome.models, shownTime]);
  const snapshots = useMemo(() => outcome.models.map(m => snapshot(m, shownTime)), [outcome.models, shownTime]);
  const tick = outcome.models[2]?.base ?? 1;
  useEffect(() => {
    if (!playing || outcome.error) return;
    const timer = setInterval(() => setTime(t => Math.min(maxTime, t + tick)), 350);
    return () => clearInterval(timer);
  }, [playing, maxTime, tick, outcome.error]);
  const sim = outcome.models.find(m => m.kind === focus);
  const snap = useMemo(() => sim ? snapshot(sim, shownTime) : null, [sim, shownTime]);
  const pageStart = Math.min(Math.floor(Math.max(0, address) / 4) * 4, settings.capacity - 48);
  const inspected = snap?.memory[Math.min(selectedAddress, settings.capacity - 1)];
  const enabled = selected(settings.mask);
  const scheduleInfo = outcome.error ? null : schedule(settings);
  const inspect = (kind: Kind, addr: number) => { setFocus(kind); setAddress(addr); setSelectedAddress(addr); };
  const setPeriod = (i: number, value: number) => setSettings(s => ({ ...s, periods: s.periods.map((v, j) => i === j ? value : v) }));
  const choosePreset = (preset: typeof PRESETS[number]) => { setSettings(s => ({ ...s, ...preset, mask: preset.mask | (s.mask & ~15), periods: sensorsFor(s).map((_, i) => preset.periods[i] ?? preset.commonPeriod) })); setTime(240); setPlaying(false); };
  const updateSensor = (i: number, patch: Partial<(typeof SENSORS)[number]>) => setSettings(s => ({ ...s, sensors: sensorsFor(s).map((sensor, j) => i === j ? { ...sensor, ...patch } : sensor) }));
  const addSensor = () => setSettings(s => {
    const current = sensorsFor(s);
    if (current.length >= MAX_SENSORS) return s;
    const type = (['extra1', 'extra2', 'extra3', 'extra4'] as const).find(type => !current.some(sensor => sensor.type === type))!;
    const name = LABELS[type];
    return { ...s, sensors: [...current, { name, short: name, type, payload: 5, raw: [], example: 'Illustrative zero bytes' }], periods: [...s.periods, s.commonPeriod], mask: s.mask | (1 << current.length) };
  });
  const removeSensor = (i: number) => setSettings(s => ({ ...s, sensors: sensorsFor(s).filter((_, j) => i !== j), periods: s.periods.filter((_, j) => i !== j), mask: (s.mask & ((1 << i) - 1)) | ((s.mask >> (i + 1)) << i) }));
  const nextWake = () => { const next = outcome.models.flatMap(m => m.records.map(r => r.time)).filter(t => t > shownTime); setTime(next.length ? Math.min(...next) : maxTime); };
  const latestRecord = sim && [...sim.records].reverse().find(r => r.time <= shownTime && (focus !== 'partitioned' || r.stream === (enabled.includes(stream) ? stream : enabled[0])));
  return <main>
    <a href="#controls" className="skip-link">Skip to comparison controls</a>
    <header><Link href="/" className="brand">densor<span> / EEPROM LAB</span></Link><nav aria-label="Page"><a href="#inspector">Byte inspector</a><a href="#changes">What changed</a><a href="#sources">Sources <span aria-hidden="true">↗</span></a></nav><span className="lab-label"><i /> INTERACTIVE PROTOCOL ATLAS</span></header>
    <section className="intro"><div><span className="eyebrow">FIRMWARE EVOLUTION / 01—04</span><h1>See the page crossings<br />your firmware avoids.</h1><p>Track baseline → R1 → R2 shared → R3 partitioned.<br className="desktop-break" /> Count the savings and see exactly where each record lands.</p></div><div className="intro-aside"><span className="eyebrow">THE SAME MEMORY.<br />FOUR WAYS TO USE IT.</span><div className="mini-pages" aria-hidden="true">{Array.from({ length: 16 }, (_, i) => <i key={i} style={{ background: ['#acb6a8', '#ab9253', '#447951', '#468483'][Math.floor(i / 4)] }} />)}</div></div></section>

    <section className="controls panel" id="controls" aria-label="Comparison settings">
      <div className="control-top"><div className="preset-group" role="group" aria-label="Presets">{PRESETS.map(p => <button key={p.name} aria-pressed={p.mask === (settings.mask & 15) && p.commonPeriod === settings.commonPeriod && p.periods.every((n, i) => n === settings.periods[i])} onClick={() => choosePreset(p)}>{p.name}</button>)}</div><label className="inline-field">Tag capacity <select value={settings.capacity} onChange={e => setSettings(s => ({ ...s, capacity: Number(e.target.value) }))}><option value={512}>512 B</option><option value={2048}>2 KiB</option><option value={8192}>8 KiB</option></select></label><button className="text-button" onClick={() => { setSettings({ ...DEFAULTS, periods: [...DEFAULTS.periods] }); setTime(240); setPlaying(false); }}>Reset ↺</button></div>
      <div className="sensor-controls">{sensors.map((sensor, i) => <div key={sensor.type} className={`sensor-field ${!(settings.mask & (1 << i)) ? 'disabled' : ''}`}>
        <div className="sensor-name-row"><label className="sensor-toggle"><input aria-label={`Enable ${sensor.short}`} type="checkbox" checked={!!(settings.mask & (1 << i))} onChange={() => setSettings(s => ({ ...s, mask: s.mask ^ (1 << i) }))} /><i style={{ background: COLORS[sensor.type] }} />{i < 4 ? sensor.short : null}</label>{i >= 4 && <><input className="sensor-name" aria-label={`Sensor ${i + 1} name`} maxLength={32} value={sensor.short} onChange={e => updateSensor(i, { name: e.target.value, short: e.target.value })} /><button className="remove-sensor" aria-label={`Remove ${sensor.short}`} onClick={() => removeSensor(i)}>×</button></>}</div>
        <label className="period-field"><span>every</span><input aria-label={`${sensor.name} period in seconds`} type="number" min={1} max={3540} step={1} value={Number.isNaN(settings.periods[i]) ? '' : settings.periods[i]} disabled={!(settings.mask & (1 << i))} onChange={e => setPeriod(i, e.target.valueAsNumber)} /><span>s</span></label>
        <label className="period-field payload-field"><span>payload</span><input aria-label={`${sensor.name} payload bytes`} type="number" min={1} max={64} step={1} value={Number.isNaN(sensor.payload) ? '' : sensor.payload} onChange={e => updateSensor(i, { payload: e.target.valueAsNumber })} /><span>B</span></label>
      </div>)}<div className="sensor-actions"><button className="secondary-button" onClick={addSensor} disabled={sensors.length >= MAX_SENSORS}>+ Add sensor</button><span>{sensors.length} / {MAX_SENSORS} sensors · 1–64 B each</span></div><div className="common-field"><label htmlFor="common-period">Baseline & R1</label><div className="period-field"><span>all every</span><input id="common-period" type="number" min={1} max={3540} value={Number.isNaN(settings.commonPeriod) ? '' : settings.commonPeriod} onChange={e => setSettings(s => ({ ...s, commonPeriod: e.target.valueAsNumber }))} /><span>s</span></div></div></div>
      <div className="control-note"><span>Periods above apply to R2/3. Baseline and R1 use the common period.</span><span>{scheduleInfo ? <>Base tick <b>{scheduleInfo.base} s</b> · Cycle <b>{formatTime(scheduleInfo.base * scheduleInfo.lcm)}</b></> : 'Choose a valid schedule.'}</span></div>
    </section>
    <p className={`layout-mode ${exploratory ? 'exploratory' : ''}`} role="status">{exploratory ? 'Exploratory layout: payload sizes or sensor slots differ from the firmware. All four layouts use these choices for comparison; TMP119 stays excluded from baseline. R3 reserves an extra 8 B pointer pair per added sensor. Header fields and schedules otherwise use the existing model; these are geometry estimates, not importable firmware records.' : 'Firmware layout: the original four sensors with 2 / 2 / 2 / 6 B payloads. Edit payload bytes or add a sensor to explore other packing choices.'} Presets change sampling schedules; Reset restores the original sensors and payloads.</p>
    {outcome.error ? <div className="error" role="alert">{outcome.error}</div> : <>
      <section className="scrubber" aria-label="Recording timeline"><div className="time-label"><span className="eyebrow">RECORDING CURSOR</span><strong>{formatTime(shownTime)}</strong></div><button className="play-button" aria-label={playing && shownTime < maxTime ? 'Pause recording' : 'Play recording'} onClick={() => { if (shownTime >= maxTime) setTime(0); setPlaying(p => !p || shownTime >= maxTime); }}>{playing && shownTime < maxTime ? 'Ⅱ' : '▶'}</button><div className="timeline"><input type="range" aria-label="Elapsed recording time in seconds" min={0} max={maxTime} step={1} value={shownTime} onChange={e => { setTime(Number(e.target.value)); setPlaying(false); }} /><div><span>0 s · first sample included</span><span>{formatTime(maxTime)} · final capacity limit</span></div></div><label className="time-input"><input aria-label="Elapsed seconds" type="number" min={0} max={maxTime} value={shownTime} onChange={e => { if (Number.isFinite(e.target.valueAsNumber)) setTime(Math.max(0, Math.min(maxTime, e.target.valueAsNumber))); setPlaying(false); }} />s</label><button className="step-button" onClick={nextWake}>Next sample →</button></section>
      <div className="section-heading crossing-heading"><h2>Crossings avoided versus baseline</h2><div className="segmented metric-toggle" role="group" aria-label="Page crossing metric"><button aria-pressed={metric === 'avoidableCrossings'} onClick={() => setMetric('avoidableCrossings')}>Alignment overhead</button><button aria-pressed={metric === 'payloadCrossings'} onClick={() => setMetric('payloadCrossings')}>Payload boundaries</button><button aria-pressed={metric === 'totalCrossings'} onClick={() => setMetric('totalCrossings')}>All boundaries</button><button aria-pressed={metric === 'crossingCommands'} onClick={() => setMetric('crossingCommands')}>Cross-page writes</button></div></div>
      <p className="metric-definition">{metric === 'payloadCrossings' ? 'Payload boundaries counts page boundaries inside each sensor’s configured payload. It excludes supply, mask, CRC, padding and pointers. A payload larger than four bytes always crosses at least one boundary. The packing comparison below separates padding savings from changes in layout and sample counts.' : metric === 'avoidableCrossings' ? 'Alignment overhead counts extra pages touched beyond the minimum for each record or pointer. A correctly aligned 16-byte record needs four pages: those three normal boundaries are not counted as overhead.' : metric === 'totalCrossings' ? 'All boundaries counts every four-byte boundary inside each logical record or pointer write, including necessary boundaries in long records. Changes in payload size and sampling rate affect these totals.' : 'Cross-page writes counts I²C write commands spanning a page boundary. The baseline sends unsplit writes; R1, R2 and R3 split each write at page boundaries, so no individual command straddles a page.'} Counts run from t = 0 through the cursor; pointer checkpoints are included only in the record-and-pointer metrics.</p>
      <section className="comparison" aria-label="Revision comparison">{outcome.models.map(model => <Overview key={model.kind} sim={model} time={shownTime} active={focus === model.kind} reference={crossingTotals[0]} metric={metric} onInspect={addr => inspect(model.kind, addr)} />)}</section>
      <div className="map-footer"><Legend sensors={sensors} types={['meta', 'pointer', ...sensors.map(s => s.type), 'supply', 'crc', 'pad', 'mask', 'free']} /><p>Maps use one scale per tag size; each tile contains {settings.capacity / 128 / 4} four-byte {settings.capacity === 512 ? 'page' : 'pages'}. Initialization, status, stop/full/error checkpoints, and post-full writes are excluded from page totals.</p></div>
      <div className="comparison-notes"><p><b>Separate alignment from workload.</b> Use “Matched workload” to give every version the same original sensors and periods. Multirate changes total record traffic; alignment overhead isolates extra page touches caused by unaligned starts. Baseline has no TMP119. {settings.capacity !== 8192 && 'Its capacity here is normalized to the selected tag; the historical firmware hard-coded 8192 bytes.'} Capacity is not a measure of energy consumption.</p><button className="secondary-button" onClick={() => download(settings, shownTime, outcome.models)}>Export comparison ↓</button></div>

      <PackingSavings models={outcome.models} totals={crossingTotals} />
      <PageCrossingExamples models={outcome.models} time={shownTime} onInspect={inspect} />
      <section className="inspector-section" id="inspector"><div className="section-heading"><div><span className="eyebrow">LOOK CLOSER</span><h2>The four-byte page is the unit that matters.</h2></div><span>Little-endian fields · synthetic record values</span></div>
        <div className="inspector panel"><div className="inspector-tabs" role="group" aria-label="Inspect a revision">{KINDS.map(k => <button key={k} aria-pressed={focus === k} onClick={() => inspect(k, outcome.models.find(m => m.kind === k)!.start)}>{NAMES[k]}<small>{SUBTITLES[k]}</small></button>)}</div>
          {sim && snap && <div className="inspector-body"><div className="byte-view"><div className="byte-toolbar"><div className="segmented" role="group" aria-label="Jump to memory area"><button onClick={() => inspect(focus, 0)}>Header</button><button onClick={() => inspect(focus, focus === 'baseline' ? 4 : focus === 'r1' ? 8 : 136)}>Pointer</button><button disabled={!latestRecord} onClick={() => latestRecord && inspect(focus, latestRecord.address)}>Record at cursor</button></div>{focus === 'partitioned' && <select aria-label="Partition to inspect" value={enabled.includes(stream) ? stream : enabled[0]} onChange={e => { const i = Number(e.target.value); setStream(i); inspect(focus, sim.regions.find(r => r.stream === i)!.start); }}>{enabled.map(i => <option key={i} value={i}>{sensors[i].short}</option>)}</select>}</div>
            <div className="address-toolbar"><span className="eyebrow">ABSOLUTE ADDRESS</span><label>Jump to <input aria-label="Jump to decimal byte address" type="number" min={0} max={settings.capacity - 1} value={address} onChange={e => { const v = e.target.valueAsNumber; if (Number.isFinite(v)) { const a = Math.max(0, Math.min(settings.capacity - 1, v)); setAddress(a); setSelectedAddress(a); } }} /></label><div><button aria-label="Previous 12 pages" disabled={pageStart === 0} onClick={() => setAddress(Math.max(0, pageStart - 48))}>←</button><button aria-label="Next 12 pages" disabled={pageStart + 48 >= settings.capacity} onClick={() => setAddress(Math.min(settings.capacity - 48, pageStart + 48))}>→</button></div></div>
            <div className="page-labels"><span>PAGE / ADDRESS</span>{[0, 1, 2, 3].map(i => <span key={i}>+{i}</span>)}</div>
            <div className="byte-grid">{Array.from({ length: 12 }, (_, row) => <div className="byte-row" key={row}><span className="byte-address"><b>{Math.floor(pageStart / 4) + row}</b>0x{hex(pageStart + row * 4, 4)}</span>{snap.memory.slice(pageStart + row * 4, pageStart + row * 4 + 4).map((b, col) => { const a = pageStart + row * 4 + col; return <button key={col} className={`byte-cell byte-${b.type} ${a === selectedAddress ? 'selected-byte' : ''}`} style={{ backgroundColor: COLORS[b.type] }} aria-label={`Address ${a}: ${b.label}${b.value !== null ? `, hex ${hex(b.value)}` : ', symbolic'}`} title={b.label} onClick={() => setSelectedAddress(a)}><b>{b.value === null ? '··' : hex(b.value)}</b><small>{ABBR[b.type]}</small></button>; })}</div>)}</div>
            <div className="byte-detail" role="status"><span className="mono">0x{hex(Math.min(selectedAddress, settings.capacity - 1), 4)}</span><span>{inspected?.label}{inspected?.time !== undefined ? ` · acquired at ${formatTime(inspected.time)}` : ''}</span></div><p className="fine-print">Each row is one four-byte page. Hex bytes are illustrative measurements; “··” denotes symbolic metadata or unused space. This view is not a complete EEPROM dump.</p>
          </div><aside className="layout-explanation"><span className="eyebrow">{NAMES[focus]} / LAYOUT NOTES</span><h3>{SUBTITLES[focus]}</h3><p>{DETAILS[focus]}</p><div className="record-metrics"><div><strong>{latestRecord ? latestRecord.bytes.length : '—'} B</strong><span>selected record</span></div><div><strong>{latestRecord ? pageTouches(latestRecord.address, latestRecord.bytes.length) : '—'}</strong><span>pages touched</span></div><div><strong>{snap.pointers.map(p => `0x${hex(p, 4)}`).join(' / ')}</strong><span>simulated hot {snap.pointers.length > 1 ? 'pointers' : 'pointer'}</span></div></div><p className="fine-print">Record metrics use the latest stored record at the cursor{focus === 'partitioned' ? ' in the chosen partition' : ''}. Page touches are geometry, not measured programming cycles.</p>
            <details open><summary>Address map <span>decimal · end exclusive</span></summary><table className="address-table"><tbody>{metadata(focus, sim.sensors).map(r => <tr key={r.start}><td>{r.start}–{r.end}</td><td>{r.name}</td></tr>)}{sim.regions.map(r => <tr key={`r${r.start}`}><td>{r.start}–{r.end}</td><td>{r.name} · {r.end - r.start} B</td></tr>)}</tbody></table></details>
            <div className="limit-note"><b>{snap.full ? 'Capacity limit reached' : 'Capacity forecast'}</b><span>{sim.stopReason} · {formatTime(sim.stopAt)}</span><span>Last stored wake: {formatTime(sim.lastAt)}. {focus === 'baseline' ? 'Original firmware may keep acquiring after writes fail.' : focus === 'partitioned' ? 'Every due stream is preflighted before any write.' : 'Only complete records are counted.'}</span></div>
          </aside></div>}
        </div>
      </section>

      <section className="scheduling panel"><div className="scheduler-copy"><span className="eyebrow">a → b / SAME RECORD LAYOUT</span><h2>Change the clock.<br />Keep the bytes.</h2><div className="segmented scheduler-toggle" role="group" aria-label="Scheduler explanation"><button aria-pressed={scheduler === 'fsm'} onClick={() => setScheduler('fsm')}>a · Retained FSM</button><button aria-pressed={scheduler === 'rtc'} onClick={() => setScheduler('rtc')}>b · RTC timer</button></div><p>{scheduler === 'fsm' ? 'Variant a retains the current stage and next tick in RTC RAM, advancing the stage after the logging transaction commits.' : 'Variant b derives the slot from elapsed RTC time divided by the base period, then checks the next tick to prevent duplicates.'}</p><p>Both read the RTC on every wake. Neither adds a timestamp to each record. Phase loss closes the session; it does not backfill missed samples.</p><span className="scheduler-byte mono">Header byte 19: {scheduler === 'fsm' ? '01' : '02'} · header CRC at 74–75 changes</span></div><div className="schedule-view"><div className="section-heading"><h3>Who is due on each tick?</h3><span>T₀ = {tick} s</span></div><div className="schedule-scroll"><div className="schedule-grid" style={{ gridTemplateColumns: `100px repeat(${Math.min((scheduleInfo?.lcm ?? 1) + 1, 13)}, minmax(28px, 1fr))` }}><span className="eyebrow">ELAPSED (s)</span>{Array.from({ length: Math.min((scheduleInfo?.lcm ?? 1) + 1, 13) }, (_, t) => <button key={t} onClick={() => { setTime(t * tick); setPlaying(false); }} aria-label={`Move cursor to ${t * tick} seconds`}>{t * tick}</button>)}{sensors.map((s, i) => <div className="schedule-row" key={i}><span>{s.short}</span>{Array.from({ length: Math.min((scheduleInfo?.lcm ?? 1) + 1, 13) }, (_, t) => <span className="schedule-cell" key={t} title={!(settings.mask & (1 << i)) ? 'Disabled' : t * tick % settings.periods[i] === 0 ? 'Due' : 'Not due'}><i style={{ background: settings.mask & (1 << i) && t * tick % settings.periods[i] === 0 ? COLORS[s.type] : 'transparent' }}>{settings.mask & (1 << i) && t * tick % settings.periods[i] === 0 ? '●' : '·'}</i></span>)}</div>)}</div></div><p className="fine-print">{(scheduleInfo?.lcm ?? 1) > 12 ? 'First 13 ticks shown. ' : 'One cycle plus its repeating boundary. '}The cycle is {scheduleInfo?.lcm} ticks ({formatTime((scheduleInfo?.lcm ?? 1) * tick)}); all enabled sensors are due at tick zero.</p><div className="counts"><span className="eyebrow">STORED ACQUISITIONS AT {formatTime(shownTime)}</span><table><thead><tr><th scope="col">Stream</th>{KINDS.map(k => <th scope="col" key={k}>{NAMES[k]}</th>)}</tr></thead><tbody>{sensors.map((s, i) => <tr key={i}><th scope="row">{s.short}</th>{outcome.models.map((m, j) => <td key={m.kind}>{m.kind === 'baseline' && i === 1 ? 'N/A' : snapshots[j].counts[i]}</td>)}</tr>)}</tbody></table></div></div></section>
    </>}

    <section id="changes" className="changes"><div className="section-heading"><div><span className="eyebrow">THE EVOLUTION</span><h2>What each revision changes</h2></div></div><div className="table-scroll"><table className="comparison-table"><thead><tr><th scope="col">Design choice</th>{KINDS.map(k => <th scope="col" key={k}>{NAMES[k]}</th>)}</tr></thead><tbody>
      <tr><th scope="row">Firmware log starts</th><td>9 B</td><td>128 B</td><td>168 B (v5)</td><td>168 B (v5)</td></tr>
      <tr><th scope="row">Record organization</th><td>Packed combined</td><td>Padded combined</td><td>Variable due-mask records</td><td>One fixed stream per partition</td></tr>
      <tr><th scope="row">Default firmware lengths</th><td>10 B with original 3 streams</td><td>16 B with all 4 streams</td><td>8–16 B per nonempty wake</td><td>4 / 4 / 4 / 8 B per stream</td></tr>
      <tr><th scope="row">Padding rule</th><td>None</td><td>Round up to 4 B</td><td>Round up to 4 B</td><td>Add 1 B only if remainder = 3</td></tr>
      <tr><th scope="row">Record integrity</th><td>No CRC</td><td>No CRC</td><td>CRC8 per combined record</td><td>CRC8 per stream record</td></tr>
      <tr><th scope="row">Durable pointer</th><td>LE16 at 7–8 · crosses page</td><td>LE16 at 8–9 · one page</td><td>1 A/B pair used; 32 B reserved</td><td>4 A/B pairs at 136–167</td></tr>
      <tr><th scope="row">Pointer updates</th><td>Raw pointer each wake</td><td>Raw pointer each record</td><td colSpan={2}>Hot pointers in 64 B RTC RAM; EEPROM checkpoints every min(LCM, 64) committed ticks, complete cycles, and stop/full/error</td></tr>
      <tr><th scope="row">Sampling / time</th><td>Common period</td><td>Common period; nominal elapsed</td><td colSpan={2}>Independent periods. a: retained FSM. b: elapsed RTC time. No per-record timestamps.</td></tr>
      <tr><th scope="row">End of space</th><td>Reject if end ≥ limit; acquisition may continue</td><td>Exact fit allowed; FULL stops acquisition</td><td>Next whole record must fit</td><td>Any due full partition closes session</td></tr>
    </tbody></table></div></section>
    <section className="sources" id="sources"><div><span className="eyebrow">GROUNDED IN THE REPOSITORY</span><h3>A protocol model, not a hardware measurement.</h3><p>Layout rules follow the original firmware, R1 v3, and the current R2/R3 format (header marker 5). R2 is shared; R3 is partitioned. Header boundaries already describe the regions; Android calculates their sizes. Default payloads match the repository’s golden fixtures. Edited payload sizes and extra sensors extend these rules as exploratory geometry; they do not change the firmware or its supported format. CRCs detect errors; they do not make a multi-page write atomic.</p></div><div className="source-links"><a href="/sources/baseline-main.c" target="_blank" rel="noreferrer">Baseline firmware · 7aa87d5 ↗</a><a href="/sources/r1-protocol.md" target="_blank" rel="noreferrer">R1 protocol v3 ↗</a><a href="/sources/multirate-protocol.md" target="_blank" rel="noreferrer">Current R2/R3 protocol ↗</a><a href="/sources/fixture-manifest.json" target="_blank" rel="noreferrer">Golden EEPROM fixtures ↗</a><a href="/sources/provenance.json" target="_blank" rel="noreferrer">Source provenance ↗</a></div></section>
    <footer><span className="brand">densor<span> / EEPROM LAB</span></span><span>4-byte pages. Explicit tradeoffs. No hidden timestamps.</span></footer>
  </main>;
}
