#!/usr/bin/env python3
"""Exercise all selected firmware modules under ASan/UBSan and emit real writer fixtures."""
import argparse
import shutil
import json
import os
from pathlib import Path
import subprocess
import sys
ROOT = Path(__file__).resolve().parents[1]
CORE = ROOT / 'DentalSensor_StorageProject/Core'
OUT = ROOT / 'build/multirate-tests'
OUT.mkdir(parents=True, exist_ok=True)
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('--update-fixtures',action='store_true',help='Replace checked phone/debug examples with firmware writer output')
args=parser.parse_args()
def run(argv):
    p = subprocess.run([str(x) for x in argv], text=True, capture_output=True)
    if p.returncode:
        print(p.stdout + p.stderr); raise subprocess.CalledProcessError(p.returncode, argv)
    return p.stdout
for storage, sid in [('partitioned',1),('shared',2)]:
    for timing, tid in [('fsm',1),('rtc',2)]:
        exe = OUT / f'test-{storage}-{timing}'
        run([os.environ.get('CC','clang'), '-std=c11','-Wall','-Wextra','-Werror','-g','-fsanitize=address,undefined',
             f'-DDENSOR_STORAGE={sid}', f'-DDENSOR_TIMING={tid}', '-I'+str(CORE/'Inc'), ROOT/'tests/test_multirate.c',
             *[CORE/'Src'/f'{n}.c' for n in ['densor_r1','densor_multirate',f'densor_logger_{storage}',f'densor_scheduler_{timing}']], '-o',exe])
        print(run([exe]).strip(), flush=True)
        board=OUT/f'board-{storage}-{timing}'
        run([os.environ.get('CC','clang'),'-std=c11','-Wall','-Wextra','-Werror','-g','-fsanitize=address,undefined',
             '-DDENSOR_MULTIRATE',f'-DDENSOR_STORAGE={sid}',f'-DDENSOR_TIMING={tid}',
             '-I'+str(ROOT/'tests/board_hal'),'-I'+str(CORE/'Inc'),ROOT/'tests/test_board_multirate.c',
             *[CORE/'Src'/f'{n}.c' for n in ['densor_board','tmp119','densor_r1','densor_multirate',f'densor_logger_{storage}',f'densor_scheduler_{timing}']],'-o',board])
        cases=['running','stopped','full','error','configuring','cold','late','early','pending-stop',
               'missing-sensor','tmp-bus','clock-invalid','startup-1','startup-59','write-fail','ready-fail','rtc-write-fail']
        for case in cases:
            for period in [1,10,120,600,3540]: run([board,case,period])
        print(f'Board {storage}/{timing}: {len(cases)*5} production control/alarm checks passed',flush=True)

        for cap in [512,2048,8192]:
            for mask in range(1,16):
                for kind in [0,1]:
                    run([exe,'--dump',OUT/f'{storage}-{timing}-{cap}-{mask}-{kind}.bin',mask,cap,kind])
print('360 full EEPROM fixtures generated by the C writers', flush=True)

JAVA = ROOT / 'source_ST25NFCApplication_V3_9/app/src/main/java/com/st/st25nfc/densor'
run(['javac','-d',OUT,JAVA/'DensorProtocol.java',JAVA/'DensorMultirate.java',JAVA/'data/DensorDataSample.java',JAVA/'data/DensorDataSet.java',ROOT/'tests/MultirateProtocolTest.java'])
print(run(['java','-ea','-cp',OUT,'MultirateProtocolTest',OUT]).strip())

# Apply actual Android-generated requests, then read the resulting committed sessions.
for request in sorted(OUT.glob('*.request')):
    storage,timing,*_=request.stem.split('-')
    run([OUT/f'test-{storage}-{timing}','--apply-request',request.with_suffix('.bin'),request,OUT/(request.stem+'-applied.bin')])
print(run(['java','-ea','-cp',OUT,'MultirateProtocolTest','--verify-applied',OUT]).strip())

# Independent fixed byte vectors, including signed payloads and supply on mixed wakes.
for row in json.loads((ROOT/'tests/multirate-record-fixtures.json').read_text()):
    for storage in ['partitioned','shared']:
        b=(OUT/f'{storage}-fsm-2048-{row["mask"]}-0.bin').read_bytes()
        if storage=='shared':
            expected=bytes.fromhex(row['shared']); assert b[168:168+len(expected)]==expected
        else:
            for i,hex_bytes in row['partitioned'].items():
                at=int.from_bytes(b[52+2*int(i):54+2*int(i)],'little')
                expected=bytes.fromhex(hex_bytes); assert b[at:at+len(expected)]==expected
print('Independent golden record bytes match all masks')

APP=ROOT/'source_ST25NFCApplication_V3_9/app'
for storage in ['partitioned','shared']:
    for timing in ['fsm','rtc']:
        source=OUT/f'{storage}-{timing}-2048-15-0.bin'
        for folder in ['src/androidTest/assets','src/debug/assets/densor-debug']:
            target=APP/folder/f'multirate-{storage}-{timing}.bin'
            if args.update_fixtures: shutil.copyfile(source,target)
            assert source.read_bytes()==target.read_bytes(), f'Firmware/phone fixture mismatch: {target}'
print('All checked Android and debug fixtures match firmware writer output')
